sudo: required
services:
  - docker

before_install:
  - docker build -t adnan1relifin/docker-react-ts -f Dockerfile.dev .

script:
  - docker run -e CI=true adnan1relifin/docker-react-ts npm run test
